enabled  = true;
selector = "mail";

domain {
  citizenhousing.in {
    path     = "/var/lib/rspamd/dkim/citizenhousing.in/mail.private";
    selector = "mail";
  }
  civiltechstudio.com {
    path     = "/var/lib/rspamd/dkim/civiltechstudio.com/mail.private";
    selector = "mail";
  }
}
