# ============================================================
#  Dovecot — Main Config
# ============================================================

# Protocols to serve
protocols = imap pop3 lmtp sieve

# Include modular config
!include conf.d/*.conf

# Log to stdout (Docker-friendly)
log_path = /dev/stdout
info_log_path = /dev/stdout
debug_log_path = /dev/stderr
