import { Router } from "express";
import path from "path";
import fs from "fs";
import { requireAuth } from "../middleware/auth.js";
import {
  listLocalFiles, uploadLocalFile, streamLocalFile,
  statLocalFile, deleteLocalFile, mkdirLocal, renameLocal,
  userRootPath,
} from "../services/localFileService.js";
import { config } from "../config/index.js";

// Office blank templates (generated by scripts/generate-templates.mjs)
const OFFICE_TEMPLATES: Record<string, Buffer> = {};
for (const ext of ["docx", "xlsx", "pptx"]) {
  const p = path.resolve(__dirname, `../templates/blank.${ext}`);
  if (fs.existsSync(p)) OFFICE_TEMPLATES[ext] = fs.readFileSync(p);
}

const router = Router();
router.use(requireAuth);

// GET /files/storage-info
router.get("/storage-info", (req, res) => {
  const hostBase = config.LOCAL_FILES_HOST_PATH ?? config.LOCAL_FILES_ROOT;
  const email = req.user!.sub.replace(/[^a-zA-Z0-9._-]/g, "_");
  res.json({
    driver: "local",
    location: `${hostBase.replace(/[\/]+$/, "")}\${email}`,
  });
});

// GET /files?path=/some/dir
router.get("/", async (req, res, next) => {
  try {
    const files = await listLocalFiles(req.user!.sub, (req.query.path as string) || "/");
    res.json(files);
  } catch (e) { next(e); }
});

// POST /files/upload?path=/some/dir/file.txt   (raw body)
router.post("/upload", async (req, res, next) => {
  try {
    const filePath = (req.query.path as string) || "/untitled";
    const chunks: Buffer[] = [];
    req.on("data", (c: Buffer) => chunks.push(c));
    req.on("end", async () => {
      try {
        await uploadLocalFile(req.user!.sub, filePath, Buffer.concat(chunks));
        res.json({ ok: true });
      } catch (e) { next(e); }
    });
  } catch (e) { next(e); }
});

// GET /files/download?path=/some/file.txt
router.get("/download", async (req, res, next) => {
  try {
    const filePath = (req.query.path as string) || "/";
    const stat = await statLocalFile(req.user!.sub, filePath);
    if (stat.isDirectory()) { res.status(400).json({ error: "Cannot download a directory" }); return; }
    const name = path.basename(filePath);
    res.setHeader("Content-Disposition", `attachment; filename="${encodeURIComponent(name)}"`);
    res.setHeader("Content-Length", stat.size);
    streamLocalFile(req.user!.sub, filePath).pipe(res);
  } catch (e) { next(e); }
});

// POST /files/mkdir   body: { path: "/new/folder" }
router.post("/mkdir", async (req, res, next) => {
  try {
    await mkdirLocal(req.user!.sub, req.body?.path || "/untitled");
    res.json({ ok: true });
  } catch (e) { next(e); }
});

// POST /files/create-folder   body: { path: "/new/folder/" }  (legacy compat)
router.post("/create-folder", async (req, res, next) => {
  try {
    await mkdirLocal(req.user!.sub, req.body?.path || "/untitled");
    res.json({ ok: true });
  } catch (e) { next(e); }
});

// POST /files/create   body: { path: "/file.txt" }  — create blank/template file
router.post("/create", async (req, res, next) => {
  try {
    const filePath = (req.body?.path as string) || "/untitled.txt";
    const ext = filePath.split(".").pop()?.toLowerCase() ?? "";
    const textTemplates: Record<string, string> = {
      md: "# Untitled\n\n",
      csv: "Column A,Column B,Column C\n",
      html: "<!DOCTYPE html>\n<html>\n<head><title>Untitled</title></head>\n<body>\n\n</body>\n</html>\n",
    };
    const content = OFFICE_TEMPLATES[ext] ?? Buffer.from(textTemplates[ext] ?? "");
    await uploadLocalFile(req.user!.sub, filePath, content);
    res.json({ ok: true });
  } catch (e) { next(e); }
});

// DELETE /files?path=/some/file.txt
router.delete("/", async (req, res, next) => {
  try {
    await deleteLocalFile(req.user!.sub, (req.query.path as string) || "/");
    res.json({ ok: true });
  } catch (e) { next(e); }
});

// POST /files/rename   body: { from: "/old.txt", to: "/new.txt" }
router.post("/rename", async (req, res, next) => {
  try {
    await renameLocal(req.user!.sub, req.body?.from, req.body?.to);
    res.json({ ok: true });
  } catch (e) { next(e); }
});

export default router;
