mail_location = maildir:/var/mail/vhosts/%d/%n

namespace inbox {
  inbox = yes
}

# Mail user/group (uid 5000 / gid 5000 created in Dockerfile)
mail_uid = 5000
mail_gid = 5000
mail_privileged_group = mail

# Quota
mail_plugins = $mail_plugins quota
