service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = no
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = no
  }
}

# LMTP over TCP so Postfix (separate container) can deliver mail
service lmtp {
  inet_listener lmtp {
    port = 24
  }
}

# Auth over TCP so Postfix can do SASL
service auth {
  inet_listener auth {
    port = 12
  }
  unix_listener auth-userdb {
    mode = 0600
    user = root
  }
}

service auth-worker {
  user = $default_internal_user
}

service managesieve-login {
  inet_listener sieve {
    port = 4190
  }
}
