mail_location = maildir:/var/mail/vhosts/%d/%n

namespace inbox {
  inbox = yes
}

mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
first_valid_gid = 5000
mail_privileged_group = mail

# Quota
mail_plugins = $mail_plugins quota
