ssl = required
ssl_cert = </etc/ssl/mailserver/fullchain.pem
ssl_key  = </etc/ssl/mailserver/privkey.pem
ssl_min_protocol = TLSv1.2
ssl_cipher_list  = HIGH:!SSLv2:!aNULL
ssl_prefer_server_ciphers = yes
