Foreground yes
LogFile /dev/stdout
LogTime yes
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
DatabaseDirectory /var/lib/clamav
MaxFileSize 50M
MaxScanSize 100M
ScanMail yes
ScanArchive yes
User clamav
